Build 2024-May-23 (re-run build)
monarch-initiative/mondo-ingest pull request #542
Opened 2024-05-24 19:42 UTC by twhetzel

the build was run as: sh run.sh make build-mondo-ingest -B

this was re-run due to the failure in https://github.com/monarch-initiative/mondo-ingest/pull/537

## Pre-merge checklist

### Documentation
Was the documentation added/updated under `docs/`?
- [ ] Yes
- [x] No, updates to the docs were not necessary after careful consideration

### QC
Was the full pipeline run before submitting this PR using `sh run.sh make build-mondo-ingest` on this branch (after 
`docker pull obolibrary/odkfull:dev`), and no errors occurred?
- [x] Yes
- [ ] No, there are no functional (code-related) changes to the pipeline in the PR, so no re-run is necessary
   
### New Packages
Were any new *Python packages* added?
- [ ] Yes, [requirements.txt.full](https://github.com/INCATools/ontology-development-kit/blob/master/requirements.txt.full) was updated and an [ODK issue](https://github.com/INCATools/ontology-development-kit/issues/new) submitted
- [x] No

Were any other *non-Python packages* added?
- [ ] Yes, [Dockerfile](https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile) updated and an [ODK issue](https://github.com/INCATools/ontology-development-kit/issues/new) submitted
- [x] No

### PR Review and Conversations Resolved
Has the PR been sufficiently reviewed by at least 1 team member of the Mondo Technical team and all threads resolved?
- [x] Yes

2024-05-24 20:51 UTC, joeflack4 commented on src/ontology/lexmatch/README.md
## What's this build for?
Is this a routine build or is this build linked to another PR or issue?

2024-05-24 20:53 UTC, joeflack4 commented on src/ontology/lexmatch/README.md
Also, I wrote a thread in a recent PR, IDR if I got a response, but I'm generally not sure of what to do when reviewing builds. I mostly just face check slurp and lexmatch, and just skim through it. I spend like 1-2 minutes on that. If anyone knows of a better practice, let me know.

2024-05-25 15:54 UTC, matentzn commented on src/ontology/lexmatch/README.md
Maybe add a documentation page "How to review a data build" to the docs:

1. The data build is not reviewed for specific changes in content, but general patterns of changes. It is recommended to spend 10 minutes reviewing each databuild.
2. There are two important reasons to review databuilds: (1) looking out for large unexplainable changes and (2) increasing your familiarity with the data generated by the pipeline. The later is as important as the former: as data stewards in the Mondo Ingest pipeline you should understand all data (every single file!) that is generated insight out, and the best way to do that is to review each file many times until it sticks. It is not wrong to use a data release to ask questions like: "what is the purpose of this file?".
3. Ensure that no files are added or removed. There are few good reasons for files being added or removed and if they happen they should be explained.
4. ORDO, DOID and OMIM matches and migration files should have "reasonable" changes, i.e. be in line with one could expect as a consequence of a few weeks worth of curation (example: 1000 added lines is not a good sign, but 70 removed lines is within reason).
5. Metrics and ontology related files should change within reason (numbers like axiom counts changing in the realms of 250 plus minus are nearly always ok, changes between 250 and 1000 are worth a second look, and changes beyond 1000 merit an investigation).
6. No file should be totally empty in a data sync.


----------

From your perspective, then, you could have noticed the massive changes in NCIT, and I would have told you that there had not been an NCIT release for over a year, now there was one, and the big change is very much expected.

2024-05-25 15:54 UTC, matentzn approved these changes
Looks great, @joeflack4 maybe make issue with the one comment I made under yours!

2024-05-25 18:58 UTC, joeflack4 commented on src/ontology/lexmatch/README.md
Thanks, this guidance is beyond what I expected! Been really wondering about this since we've been more active with builds. I think it's a good idea to have a page for this. I created the issue:
- #544

There are a few docs issues piling up, so we can probably efficiently do them in a batch; like I think there's a doc-athon coming up IIRC.

2024-05-25 18:59 UTC, joeflack4 commented on src/ontology/lexmatch/README.md
There are deleted files in this PR, but it looks OK.

I noticed that there are 2 deleted files in this diff. They're both OMIMPS. I investigated, thinking that this must be because of the `www` issue. I have 2 PRs that address this, one in `omim`, and one in `mondo-ingest`, and both are basically ready to merge. I just checked the diff in the `mondo-ingest` PR, and was relieved to see that the files are not deleted there: https://github.com/monarch-initiative/mondo-ingest/pull/520/files

2024-05-25 19:00 UTC, joeflack4 approved these changes

2024-05-25 19:01 UTC, joeflack4 requested changes

2024-05-25 19:01 UTC, joeflack4 commented on src/ontology/lexmatch/split-mapping-set/mondo_broadmatch_omimps.tsv
Deleted file

2024-05-25 21:09 UTC, matentzn commented on src/ontology/lexmatch/split-mapping-set/mondo_broadmatch_omimps.tsv
Good catch! Could have been OMIMPS, but it this case it likely is not. My guess is it is related to https://github.com/monarch-initiative/mondo/pull/7563! Do you understand how the two might be related?

2024-05-25 21:56 UTC, joeflack4 commented on src/ontology/lexmatch/split-mapping-set/mondo_broadmatch_omimps.tsv
I see; I didn't know about that. In that case, I'm not sure which is the cause of OMIMPS not appearing here. If it is caused by #&563, does this (also) mean that the removal of these OMIMPS file is not a problem?

2024-05-26 06:32 UTC, matentzn commented on src/ontology/lexmatch/split-mapping-set/mondo_broadmatch_omimps.tsv
Again this is a better of judgement. Here is how my brain thinks of it:

1. If you are right (and it is related to the prefix), then _all_ omimps related files (in particular the "exact" ones) would be removed.
2. If I am right, only the non-exact ones (close, broad, etc) would be removed.

So I would check if the "exact" one is still there!

2024-05-26 17:49 UTC, twhetzel commented on src/ontology/lexmatch/split-mapping-set/mondo_broadmatch_omimps.tsv
![Screenshot 2024-05-26 at 10 48 22 AM](https://github.com/monarch-initiative/mondo-ingest/assets/2167174/fa6589cf-c312-4b8e-8c7b-cd5836d31220)

2024-05-29 22:31 UTC, joeflack4 commented on src/ontology/lexmatch/split-mapping-set/mondo_broadmatch_omimps.tsv
Ah OK, so looks like no problem then!

@twhetzel I think you said that this build is no longer relevant and was replaced by:
- #548 

So I'm going to close this. Feel free to re-open if I am incorrect about that!

2024-05-29 22:31 UTC, closed without merging